apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zj3o41hz7-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zj3o41hz7-dotnet-basic-gitops